version: "3"
services:
  node:
    build:
      context: ./
      args:
        INPUT_PACKAGE: ${INPUT_PACKAGE}
        OUTPUT_PACKAGE: ${OUTPUT_PACKAGE}
    environment:
      - INPUT_NAME=${INPUT_NAME}
      - INPUT_PACKAGE=${INPUT_PACKAGE}
      - INPUT_OPTIONS=${INPUT_OPTIONS}
      - OUTPUT_NAME=${OUTPUT_NAME}
      - OUTPUT_PACKAGE=${OUTPUT_PACKAGE}
      - OUTPUT_OPTIONS=${OUTPUT_OPTIONS}
    volumes:
      - ./:/app
